// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using PrusApp.Data;
using System;

namespace PrusApp.Migrations
{
    [DbContext(typeof(PrusContext))]
    partial class PrusContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PrusApp.Models.DistributionCenter", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("PhoneNum");

                    b.HasKey("ID");

                    b.ToTable("DistributionCenter");
                });

            modelBuilder.Entity("PrusApp.Models.Package", b =>
                {
                    b.Property<int>("PackageNumID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Product");

                    b.Property<string>("Type");

                    b.HasKey("PackageNumID");

                    b.ToTable("Package");
                });

            modelBuilder.Entity("PrusApp.Models.RouteNode", b =>
                {
                    b.Property<int>("RouteNodeID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Arrival");

                    b.Property<DateTime>("Departure");

                    b.Property<int>("DistributionCenterID");

                    b.Property<int>("PackageNumID");

                    b.HasKey("RouteNodeID");

                    b.HasIndex("DistributionCenterID");

                    b.HasIndex("PackageNumID");

                    b.ToTable("RouteNode");
                });

            modelBuilder.Entity("PrusApp.Models.RouteNode", b =>
                {
                    b.HasOne("PrusApp.Models.DistributionCenter", "DistributionCenter")
                        .WithMany("RouteNodes")
                        .HasForeignKey("DistributionCenterID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PrusApp.Models.Package", "Package")
                        .WithMany("RouteNodes")
                        .HasForeignKey("PackageNumID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
